######################################################################
# Automatically generated by qmake (3.1) Tue Jun 20 23:46:12 2017
######################################################################
QT += core gui sql testlib widgets

TEMPLATE = app
TARGET = test
INCLUDEPATH += .

QMAKE_CXX = clang++
QMAKE_CXXFLAGS += -std=c++14

DESTDIR = build/
OBJECTS_DIR = build/objects
MOC_DIR = build/mocs

DEFINES += QT_DEPRECATED_WARNINGS

HEADERS += ../src/application.h \
../src/utils/logger.h \
../src/models/connection.h \
../src/models/database.h \
../src/models/table.h \
../src/models/column.h \
../src/models/query_model.h \
../src/window/main_window.h \
../src/window/sql_editor.h \
../src/window/connection_window.h \
../src/window/db_viewer.h
../src/window/query_view.h \

SOURCES += ../src/application.cpp \
../src/models/connection.cpp \
../src/models/database.cpp \
../src/models/table.cpp \
../src/models/column.cpp \
../src/models/query_model.cpp \
../src/window/main_window.cpp \
../src/window/sql_editor.cpp \
../src/window/connection_window.cpp \
../src/window/db_viewer.cpp
../src/window/query_view.cpp \

SOURCES += src/test_application.cpp
